// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using censudex_clients_service.src.Data;

#nullable disable

namespace censudex_clients_service.src.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("censudex_clients_service.src.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Headquarters",
                            Birthdate = new DateOnly(1990, 1, 1),
                            CreatedAt = new DateOnly(2025, 10, 28),
                            Email = "admin@censudex.cl",
                            FirstName = "Admin",
                            IsActive = true,
                            LastNames = "Censudex",
                            PasswordHash = "$2a$11$Uc8ju29w6x8Z0dv6St3.De1BOELUrYXCLODoyxqpeBlrSZpCFGSS2",
                            PhoneNumber = "+56900000000",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Example Street 123",
                            Birthdate = new DateOnly(1995, 5, 10),
                            CreatedAt = new DateOnly(2025, 10, 28),
                            Email = "john@censudex.cl",
                            FirstName = "John",
                            IsActive = true,
                            LastNames = "Doe",
                            PasswordHash = "$2a$11$NwiOOAh7imEqtZupJCN3A.HjxA5nLkhb2q8SpuHvyh0CeAHyLdzG6",
                            PhoneNumber = "+56911111111",
                            Role = 0,
                            Username = "john"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "Another Street 456",
                            Birthdate = new DateOnly(2000, 3, 15),
                            CreatedAt = new DateOnly(2025, 10, 28),
                            Email = "jane@censudex.cl",
                            FirstName = "Jane",
                            IsActive = true,
                            LastNames = "Smith",
                            PasswordHash = "$2a$11$NwiOOAh7imEqtZupJCN3A.HjxA5nLkhb2q8SpuHvyh0CeAHyLdzG6",
                            PhoneNumber = "+56922222222",
                            Role = 0,
                            Username = "jane"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "Third Street 789",
                            Birthdate = new DateOnly(1998, 10, 20),
                            CreatedAt = new DateOnly(2025, 10, 28),
                            Email = "mark@censudex.cl",
                            FirstName = "Mark",
                            IsActive = true,
                            LastNames = "Brown",
                            PasswordHash = "$2a$11$NwiOOAh7imEqtZupJCN3A.HjxA5nLkhb2q8SpuHvyh0CeAHyLdzG6",
                            PhoneNumber = "+56933333333",
                            Role = 0,
                            Username = "mark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
