using censudex_clients_service.src.Helpers.Requests;
using censudex_clients_service.src.Models;

namespace censudex_clients_service.src.Repositories
{
    /// <summary>
    /// Defines the contract for client data access operations in the Censudex system.
    /// </summary>
    /// <remarks>
    /// This interface abstracts the data layer and provides methods for performing
    /// CRUD operations, querying, and business rule validation for Client entities.
    /// Implementations of this interface should handle database interactions and
    /// ensure data consistency and integrity.
    /// </remarks>
    public interface IClientRepository
    {
        /// <summary>
        /// Creates a new client in the data store and returns the created entity.
        /// </summary>
        /// <param name="client">The client entity to be created.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// the created Client entity with any database-generated values.
        /// </returns>
        /// <remarks>
        /// The implementation should ensure that the client is persisted to the data store
        /// and return the complete entity including any values generated by the database.
        /// </remarks>
        Task<Client> CreateAsync(Client client);

        /// <summary>
        /// Retrieves a paginated and filtered collection of clients from the data store.
        /// </summary>
        /// <param name="query">The query parameters containing filtering, sorting, and pagination options.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// a tuple with:
        /// - An enumerable collection of Client entities matching the query criteria
        /// - The total count of clients matching the filter criteria (before pagination)
        /// </returns>
        /// <remarks>
        /// Implementations should apply all specified filters, sorting, and pagination
        /// to the query before execution. The total count should reflect the number of
        /// records matching the filter criteria, not the paginated result set size.
        /// </remarks>
        Task<(IEnumerable<Client> Clients, int TotalCount)> GetAllAsync(ClientQuery query);

        /// <summary>
        /// Retrieves a client by their unique identifier.
        /// </summary>
        /// <param name="id">The GUID that uniquely identifies the client.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// the Client entity if found; otherwise, null.
        /// </returns>
        Task<Client?> GetByIdAsync(Guid id);

        /// <summary>
        /// Retrieves a client by their email address.
        /// </summary>
        /// <param name="email">The email address to search for.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// the Client entity if found; otherwise, null.
        /// </returns>
        /// <remarks>
        /// Implementations should perform an exact match on the email address.
        /// This method is typically used for authentication and duplicate checking.
        /// </remarks>
        Task<Client?> GetByEmailAsync(string email);

        /// <summary>
        /// Retrieves a client by their username.
        /// </summary>
        /// <param name="username">The username to search for.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// the Client entity if found; otherwise, null.
        /// </returns>
        /// <remarks>
        /// Implementations should perform an exact match on the username.
        /// This method is typically used for authentication and duplicate checking.
        /// </remarks>
        Task<Client?> GetByUsernameAsync(string username);

        /// <summary>
        /// Adds a new client to the data store without returning the created entity.
        /// </summary>
        /// <param name="client">The client entity to be added.</param>
        /// <returns>A task that represents the asynchronous operation.</returns>
        /// <remarks>
        /// This method is similar to CreateAsync but does not return the created entity.
        /// Use this method when you don't need access to database-generated values.
        /// </remarks>
        Task AddAsync(Client client);

        /// <summary>
        /// Updates an existing client in the data store.
        /// </summary>
        /// <param name="client">The client entity with updated values.</param>
        /// <returns>A task that represents the asynchronous operation.</returns>
        /// <remarks>
        /// The implementation should update all properties of the client entity
        /// in the data store. The client must exist in the data store before calling this method.
        /// </remarks>
        Task UpdateAsync(Client client);

        /// <summary>
        /// Performs a soft delete on a client by marking them as inactive.
        /// </summary>
        /// <param name="id">The GUID of the client to soft delete.</param>
        /// <returns>A task that represents the asynchronous operation.</returns>
        /// <remarks>
        /// Implementations should set the IsActive property to false instead of
        /// physically deleting the record. This preserves data history while
        /// making the client inaccessible for normal operations.
        /// </remarks>
        Task SoftDeleteAsync(Guid id);

        /// <summary>
        /// Checks whether a client with the specified email address already exists in the data store.
        /// </summary>
        /// <param name="email">The email address to check for existence.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// true if a client with the specified email exists; otherwise, false.
        /// </returns>
        /// <remarks>
        /// This method is used for validation to ensure email uniqueness during
        /// client registration and updates.
        /// </remarks>
        Task<bool> ExistsByEmailAsync(string email);

        /// <summary>
        /// Checks whether a client with the specified username already exists in the data store.
        /// </summary>
        /// <param name="username">The username to check for existence.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains
        /// true if a client with the specified username exists; otherwise, false.
        /// </returns>
        /// <remarks>
        /// This method is used for validation to ensure username uniqueness during
        /// client registration and updates.
        /// </remarks>
        Task<bool> ExistsByUsernameAsync(string username);
    }
}